name: DevSecOps CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install fastapi uvicorn

    - name: Lint Python Code
      run: |
        pip install flake8
        flake8 app/

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t secureflow-app -f docker/Dockerfile .

    - name: Scan Docker image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'secureflow-app'
        format: 'table'
        exit-code: '0'
        severity: 'CRITICAL,HIGH'

    - name: Run Semgrep Scan
      uses: returntocorp/semgrep-action@v1
      with:
        config: "auto"

    - name: Send Slack Alert on Failure
      if: failure()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_COLOR: '#FF0000'
        SLACK_MESSAGE: |
        ❌ CI Failed for *${{ github.repository }}*
        ✳️ Commit: ${{ github.sha }}
        🔗 <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Logs>

    - name: Send Slack Alert on Success
      if: success()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_COLOR: '#36a64f'
        SLACK_MESSAGE: |
        ✅ CI Succeeded for *${{ github.repository }}*
        ✳️ Commit: ${{ github.sha }}
        🔗 <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Logs>

